version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
